- .env
- package.json
- pnpm-lock.yaml
- prisma/schema.prisma
Instalación de prisma, defino modelos básicos
> feat(prisma/schema.prisma): define basics models

- app/api/reviews/route.js
Se creo el endpoint para crear y mostrar las reviews
> feat(app/api/reviews/route.js): Add GET  and POST review endpoints

- app/globals.css
> modified(app/gloabls) add variables colors

- components/NavBar.jsx
añadi las redirecciones a el logo que lleva a home, a la foto de perfil que nos lleva a la profile page y al boton de Perfil de el menu bottom que tambien nos lleva a profile page.
> fix(components/NavBar.jsx): fix 3 links

- app/login/page.jsx
- app/login/validate.js
create folder and page of the login and sing in routes
> Feat app/login/page.jsx

- app/layout.js
- app/testingredux/page.jsx
- store/provider.jsx
- store/slice.js
- store/store.js
cree la carpeta store con sus respectivos archivos modifique el layout agregando el provider y cree una ruta de renderizado para test4ear el stado global
> fed(artyfy/store ):add redux toolkits

- app/api/category/controllers.js
- app/api/category/route.js
Agregamos los metodos PUST and GET de /category.
Terminado y testeado.
> feat(api/category): create GET's and POST's.

- app/testingredux/page.jsx
arregle la page de testing del redux
> fix(/testing/page)fix fuction useState

- app/testingredux/page.jsx
- components/Card.jsx
- components/Cards.jsx
- store/slice.js
fix(app/testingredux/page.jsx): se modifico el código para redux y modificacion de card y cards
> Fix(app/testingredux/page.jsx)

- app/api/products/controllers.js
- app/api/products/route.js
Agregue enpoint para search por nombre
> feat(api/products route.js/controllers.js): search endpoint

- app/login/page.jsx
- app/login/singin/page.jsx
- app/login/singin/setCategories/page.jsx
Sign in page agregada con form funcional, le faltaria el dispatch
> Feat(login/singin/page.jsx) add singin page;

- app/api/products/controllers.js
Se arregló la validación "regex" para el nombre de los productos.
> fix(api/products controllers.js): fix regex validate

- app/page.jsx
- app/profile/layout.js
- app/profile/page.jsx
- components/Cards.jsx
- components/Filters.jsx
- components/databs.js
- next.config.js
- store/slice.js
se carga la petición al estado principal apenas renderisa la pagina
> fix(add/page.jsx):se utiliza redux y se hace llamado a servidor 

- app/api/products/[id]/controllers.js
El detail de producto, trae la imagen, email y nombre del usuario que lo subió
> fix(api/products/[id] controller.js): add user image

- app/page.jsx
- components/Cards.jsx
- store/slice.js
cambios para renderizar cards y guardado de info en estado redux
> Fix(components/cards)

- app/loading.jsx
- app/page.jsx
- components/Card.jsx
- components/Cards.jsx
> Fix(acompnents/cards) add loading

- components/Cards.jsx
- components/Filters.jsx
- store/slice.js
Incorporacion de Filtro por Provincias.
> Feat(fix front errors) dev filters

- app/page.jsx
- components/Cards.jsx
- components/Filters.jsx
- components/fetch/useFetch.js
- store/slice.js
ya sirve el filtro y agrege una nueva función para el fetch
> Fix(componenets/filters)

- components/fetch/useFetch.js
- store/slice.js
fix(store/slice.js)se arreglo el codigo de countries
> fix(store/slice.js):recoode coountrie reducer

- app/page.jsx
- app/profile/page.jsx
- components/Filters.jsx
- store/slice.js
> Fix(components/filters)

- app/page.jsx
- next.config.js
arreglar useEffect y agregar dominio para imagen
> fix(app/page.jsx&config.js):recode useEffect y agregar imagen

- components/CategoryFilter.jsx
- components/Filters.jsx
creacion de CategoryFilter.jsx y refactor Filters.jsx
> refactor(component/ filters.jsx): add CategoryFilter.jsx

- app/post-product/page.jsx
- app/post-product/validate.js
- components/Filters.jsx
categorías arregladas y validaciones implementadas, faltaría arreglar las validaciones que se muestren de a una.
> Fix(app/post product)  fix categories to checkbox;

- app/api/products/[id]/controllers.js
- app/api/products/[id]/reviews/[reviewId]/controllers.js
- app/api/products/[id]/reviews/controllers.js
- app/api/products/[id]/reviews/route.js
- app/api/products/controllers.js
- app/api/provinces/route.js
- app/api/users/[id]/controllers.js
- app/api/users/[id]/route.js
- app/api/users/controllers.js
- app/api/users/route.js
Agregue todas las validaciones para todos los metodos POST y PUT de todo el BackEnd. Solo queda validar las imagenes que no lo hice porque tengo que averiguar como se manejan el subir imagenes a una nube para usarlas. 
Las validaciones PUT son basicamente las misma que POST ya que vamos a seguir los mismos estandares de validaciones.
> feat(api/routes):addingAllPOSTandPUTvalidations.

- app/api/checkoutPro/route.js
- components/mercadoPagoButton/MpButton.jsx
- package.json
- pnpm-lock.yaml
Boton para mercado pago agregado como componente y ruta de api de compra fixeada
> Feat(components/marcado pago button)  add mp button;

- app/api/contact/route.js
- components/config/nodemailer.js
> Fix(nodemailer)

- components/buttons/AddDeductButtons.jsx
botones arreglados, dando un dato correcto en local.storage.
> fix(AddDeductButtons)fix local.storage data;

- app/post-product/page.jsx
Se agrego un redireccionamiento luego de realizar un post
> fix(app/post-product page):redirect after posting

- app/signin/page.jsx
> fix(add/signIn/page):pegue lo que me paso nahuel

- middleware.tsx
> feat(/ middleware.tsx): config middleware

- app/purchase-status/page.jsx
- components/PurchaseStatusComponent.jsx
data enviada para el envio de mails lista y ternarios para que muestre mmensaje dependiendo del status de la compra implementados.
> Fix /purchase status fix send data;

- middleware.ts
Comenté el archivo middleware.ts
> fix(/ middleware.ts): comment middleware

- components/CartComponent.jsx
- components/buttons/BuyAndDetail.jsx
ternario para que el detalle de compra solo se muestre en cart listo
> fix(components/ BuyAndDetail) fix ternario de cart

- middleware.ts
Se implementó el middleware para las rutas /settings /post-product /profile
> feat(/ middleware.ts): implement middleware

- app/api/users/controllers.js
- app/api/users/route.js
cambio de validaciones y parámetros requeridos para el handler
> refact(api/users route controller): change required values

- components/buttons/ButtonCloseCart.jsx
El numero que se muestra en el carrito de la navbar se actualiza al eliminar el total de los articulos almacenados en el localstorage
> fix(components/buttons/ ButtonCloseCart)

- prisma/migrations/20230718200734_first/migration.sql
- prisma/schema.prisma
Se actualizó el esquema de prisma
> refact(/prisma schema.prisma): update models

- app/login/page.jsx
- app/login/validate.js
- app/signin/page.jsx
- components/inputs/InputField.jsx
forms cambio en style y validaciones
> Fix forms/validate styles

- app/api/sales/[id]/controllers.js
- app/api/sales/[id]/route.js
- app/api/sales/controllers.js
- app/api/sales/route.js
Ruta y controladores del SELLER. A testiar.
> feat:addRouteOfSeller

- app/api/sales/[id]/controllers.js
- app/cart/cardCart/CardCart.jsx
- app/post-product/page.jsx
- app/purchase-status/page.jsx
- components/PurchaseStatusComponent.jsx
- components/buttons/AddDeductButtons.jsx
Elimino advertencias comentando las líneas anteriores a los arrays de dependencias de los useEffect()
// eslint-disable-next-line react-hooks/exhaustive-deps
> fix(/app): eslint-disable-next-line react-hooks/exhaustive-deps

- app/purchase-status/page.jsx
- components/NavBar/LogoutButton.jsx
url base añadida y logout button sin errores de localStorage.
> Fix /app/purchase status fix base url en peticiones;

- app/api/checkoutPro/route.js
base url cambiada a la del env.
> fix (api/checkoutPro) fix base_url;

- app/api/sales/[id]/controllers.js
Correcion del controller.js del salesId para el uso del Front.
> changesIntoIdSales

- app/api/stats/[id]/controllers.js
- app/api/stats/[id]/route.js
- app/api/stats/controllers.js
- app/api/stats/route.js
información para el dashboard separada para admin y user
> reafactor(api/stats route controllers ): 

- app/api/auth/[...nextauth]/options.ts
- components/buttons/SignInButton.tsx
- middleware.ts
Intento de solución redireccionamiento  erroneo
> fix(/middleware)
